name: taiyishenshu_example
description: "Tai Yi Shen Shu - 示例应用"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  taiyishenshu:
    git:
      url: http://xuan:***@192.168.0.165:3000/xuan/xuan-taiyishenshu.git
      ref: main
  google_fonts: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
