name: taiyishenshu_example
description: "Tai Yi Shen Shu - 示例应用"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.11.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  taiyishenshu:
    git:
      url: http://192.168.0.165:3000/xuan/xuan-taiyishenshu.git
  google_fonts: ^6.2.1
  repository_interface_taiyishenshu:
    git:
      url: http://192.168.0.165:3000/xuan/repository-interface-taiyishenshu.git
  persistence_drift:
    git:
      url: http://192.168.0.165:3000/xuan/xuan-storage.git
      path: drift
  persistence_preferences:
    git:
      url: http://192.168.0.165:3000/xuan/xuan-storage.git
      path: preferences
  persistence_assets:
    git:
      url: http://192.168.0.165:3000/xuan/xuan-storage.git
      path: assets
  shared_preferences: ^2.0.0

dependency_overrides:
  xuan_four_zhu_card:
    git:
      url: http://192.168.0.165:3000/xuan/xuan-four-zhu-card.git
  persistence_core:
    git:
      url: http://192.168.0.165:3000/xuan/xuan-storage.git
      path: core
  persistence_drift:
    git:
      url: http://192.168.0.165:3000/xuan/xuan-storage.git
      path: drift
  metaphysics_core:
    git:
      url: http://192.168.0.165:3000/xuan/metaphysics-core.git
  xuan_gua_core:
    git:
      url: http://192.168.0.165:3000/xuan/xuan-gua-core.git
  theme:
    git:
      url: http://192.168.0.165:3000/xuan/theme.git
  persistence_domain:
    git:
      url: http://192.168.0.165:3000/xuan/xuan-domain.git
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
